version: 0.2

phases:
  install:
    commands:
      # Install the packages required
      - pip install -r requirements.txt -t .
      # Upgrade AWS CLI
      - pip install --upgrade awscli
  build:
    commands:
      - aws cloudformation package --s3-bucket $S3_BUCKET --template-file template.yml --output-template-file output-template.yaml
      
artifacts:
  type: zip
  files:
    - output-template.yaml
    - '**/*'
