version: 0.2

phases:
  install:
    commands:
      # Install/upgrade pip and AWS CLI 
      - pip install --upgrade pip awscli
      # Install the packages required
      - pip install -r requirements.txt -t .
  build:
    commands:
      - aws cloudformation package --s3-bucket $LAMBDA_ARTIFACT_STORE_BUCKET --template-file template.yml --output-template-file output-template.yaml
      
artifacts:
  type: zip
  files:
    - output-template.yaml
    - '**/*'
